exp:
  parent: "v1"
  project_name: "optrade1/Version-1"
  model_id: "EMForecaster"
  seed_list: [54930]
  seed: 54930
  mae: True
  task: "forecasting"

  neptune: False
  gpu_id: 0

data:
  download_only: False
  offline: True
  clean_up: False
  dev_mode: True
  patch_dim: 8
  patch_stride: -1
  window_stride: 1
  dtype: "float32"
  seq_len: 30
  pred_len: 6
  train_split: 0.33
  val_split: 0.33
  num_channels: 1
  scale: True
  target_type: "multistep"
  verbose: True

  # Dataloader (CPU setup)
  batch_size: 128
  prefetch_factor: 0
  num_workers: 0
  persistent_workers: False
  pin_memory: False
  shuffle: True
  drop_last: False

  # # Dataloader (GPU Setup)
  # batch_size: 128
  # prefetch_factor: 4
  # num_workers: 4  # Typically set to number of CPU cores
  # persistent_workers: True
  # pin_memory: True
  # shuffle: True
  # drop_last: False

contracts:
  validate: False # Use if not using pre-downloaded data
  modify: False # DO NOT turn this on if you have pre-downloaded data (it may delete .pkl files erroneously)
  root: "AAPL"
  start_date: "20230107"
  end_date: "20231228"
  interval_min: 1
  right: "C"
  moneyness: "ATM"
  strike_band: 0.05
  volatility_scaled: False
  target_tte: 30
  tte_tolerance: [15, 45]
  stride: 3

# Features
feats:
  target_channels: ["option_returns"]
  scaling: True
  core: [
      "option_returns",
      "stock_returns",
      # "distance_to_strike",
      "moneyness",
      "option_lob_imbalance",
      "option_quote_spread",
      "stock_lob_imbalance",
      "stock_quote_spread",
      # "option_mid_price",
      # "option_bid_size",
      # "option_bid",
      # "option_ask_size",
      # "option_close",
      "option_volume",
      # "option_count",
      # "stock_mid_price",
      # "stock_bid_size",
      # "stock_bid",
      # "stock_ask_size",
      # "stock_ask",
      "stock_volume",
      # "stock_count",
    ]

  # TTE features
  tte: [
      "sqrt",
      # "exp_decay"
    ]

  # Datetime features
  datetime: [
      "sin_minute_of_day",
      # "cos_minute_of_day",
      "sin_hour_of_week",
      # "cos_hour_of_week",
    ]

eval:
  metrics: ["mse", "mae", "rmse", "r2", "mape"]
  best_model_metric: "mse"

train:
  optimizer: "adam"
  criterion: "MSE"
  scheduler: "cosine"
  dropout: 0.3
  epochs: 5
  lr: 1e-4
  early_stopping: True
  weight_decay: 1e-5
  return_head: True

  # RevIN
  revin: True
  revin_affine: True
  revout: True
  eps_revin: 1e-5

# EMForecaster
emf:
  patch_norm: "none"
  patch_act: "gelu"
  patch_embed_dim: 128
  num_enc_layers: 1
  dropout: 0.3
  patch_model_id: "TSMixer"
  d_model: 128

early_stopping:
  patience: 20
